/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
// import VuesaxLinearCategory2 from 'src/components/VuesaxLinearCategory2/VuesaxLinearCategory2';
// import VuesaxLinearSetting4 from 'src/components/VuesaxLinearSetting4/VuesaxLinearSetting4';

const TableDefault1 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `2px 4px 35px rgba(117, 121, 255, 0.18)`,
  border: `2px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `15px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `783px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  overflow: `hidden`,
}));

const Group6 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1020px`,
  height: `60px`,
  left: `62px`,
  top: `120px`,
});

const Line2 = styled('div')({
  border: `1px solid rgba(237, 238, 255, 1)`,
  width: `1020px`,
  height: `0px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Line3 = styled('div')({
  border: `1px solid rgba(237, 238, 255, 1)`,
  width: `1020px`,
  height: `0px`,
  position: `absolute`,
  left: `0px`,
  top: `60px`,
});

const Name = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(27, 28, 55, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `105px`,
  top: `21px`,
}));

const No = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(27, 28, 55, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `16px`,
  top: `21px`,
}));

const Type = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(27, 28, 55, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `368px`,
  top: `21px`,
}));

const Status = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(27, 28, 55, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `111px`,
  position: `absolute`,
  left: `586px`,
  top: `21px`,
}));

const Group7 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1020px`,
  height: `60px`,
  left: `62px`,
  top: `220px`,
});

const Line21 = styled('div')({
  border: `1px solid rgba(237, 238, 255, 1)`,
  width: `1020px`,
  height: `0px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Line31 = styled('div')({
  border: `1px solid rgba(237, 238, 255, 1)`,
  width: `1020px`,
  height: `0px`,
  position: `absolute`,
  left: `0px`,
  top: `60px`,
});

const Gillette = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(27, 28, 55, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `300`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `109px`,
  top: `21px`,
}));

const Q1 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(27, 28, 55, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `300`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `24px`,
  top: `21px`,
}));

const Playlist = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(27, 28, 55, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `200`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `369px`,
  top: `24px`,
}));

const Q1To50Pages = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(27, 28, 55, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `300`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `1032px`,
  top: `730px`,
}));

const Rectangle7 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(237, 238, 255, 1)`,
  border: `1px solid rgba(117, 121, 255, 1)`,
  boxSizing: `border-box`,
  borderRadius: `3px`,
  width: `36px`,
  height: `17px`,
  position: `absolute`,
  left: `983px`,
  top: `732px`,
}));

// const VuesaxLinearCategory = styled(VuesaxLinearCategory2)(({ theme }) => ({
//   width: `24px`,
//   height: `24px`,
//   position: `absolute`,
//   left: `1047px`,
//   top: `56px`,
// }));

// const VuesaxLinearSetting41 = styled(VuesaxLinearSetting4)(({ theme }) => ({
//   width: `24px`,
//   height: `24px`,
//   position: `absolute`,
//   left: `983px`,
//   top: `56px`,
// }));

const RoomList = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Newake`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `62px`,
  top: `42px`,
});

const Open = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(27, 28, 55, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `200`,
  fontSize: `10px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `689px`,
  top: `244px`,
}));

function TableDefault(props) {
  return (
    <TableDefault1 className={props.className}>
      <Group6>
        <Line2></Line2>
        <Line3></Line3>
        <Name>{`Name`}</Name>
        <No>{`No.`}</No>
        <Type>{`Type`}</Type>
        <Status>{`Status`}</Status>
      </Group6>
      <Group7>
        <Line21></Line21>
        <Line31></Line31>
        <Gillette>{`Gillette`}</Gillette>
        <Q1>{`1.`}</Q1>
        <Playlist>{`Playlist`}</Playlist>
      </Group7>
      <Q1To50Pages>{`1 to 50 Pages`}</Q1To50Pages>
      <Rectangle7></Rectangle7>
      {/* {false && <VuesaxLinearCategory />}
      {false && <VuesaxLinearSetting41 />} */}
      <RoomList>{`Room List`}</RoomList>
      <Open>{`Open`}</Open>
    </TableDefault1>
  );
}

export default TableDefault;
