/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import VuesaxLinearArrowLeft from 'src/components/VuesaxLinearArrowLeft/VuesaxLinearArrowLeft';
import VuesaxLinearArrowRight from 'src/components/VuesaxLinearArrowRight/VuesaxLinearArrowRight';
import Options from 'src/components/Options/Options';
import Buttons from 'src/components/Buttons/Buttons';

const AboutUs1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100vw',
  height: `1098px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Frame8 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `flex-start`,
  padding: `0px 80px`,
  boxSizing: `border-box`,
  width: `1440px`,
  left: `0px`,
  top: `50px`,
});

const Frame6 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const VuesaxLinearArrowLef = styled(VuesaxLinearArrowLeft)(({ theme }) => ({
  width: `40px`,
  height: `40px`,
  margin: `0px`,
}));

const Home = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(41, 41, 41, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `32px`,
  letterSpacing: `-1.6px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `uppercase`,
  margin: `0px 0px 0px 20px`,
});

const Frame7 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Faq = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(41, 41, 41, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `32px`,
  letterSpacing: `-1.6px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `uppercase`,
  margin: `0px`,
});

const VuesaxLinearArrowRig = styled(VuesaxLinearArrowRight)(({ theme }) => ({
  width: `40px`,
  height: `40px`,
  margin: `0px 0px 0px 20px`,
}));

const Frame51 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1440px`,
  height: `500px`,
  left: `81px`,
  top: `269px`,
});

const Frame52 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  left: `0px`,
  top: `0px`,
});

const HelloMyNameIsBrandon = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Newake`,
  fontWeight: `400`,
  fontSize: `60px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `uppercase`,
  width: `1122px`,
  margin: `0px`,
});

const Frame3 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px 80px`,
  boxSizing: `border-box`,
  width: `1440px`,
  left: `0px`,
  top: `948px`,
});

const NavigationBars = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  boxShadow: `0px 0px 50px rgba(0, 0, 0, 0.23)`,
  borderRadius: `100px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `20px 100px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
  overflow: `hidden`,
});

const Sr = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(41, 41, 41, 1)`,
  fontStyle: `normal`,
  fontFamily: `Newake`,
  fontWeight: `400`,
  fontSize: `36px`,
  letterSpacing: `-1.8px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `capitalize`,
});

const Frame53 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
});

const Options1 = styled(Options)(({ theme }) => ({
  margin: `0px`,
}));

function AboutUs(props) {
  return (
    <AboutUs1 className={props.className}>
      <Frame8>
        <Frame6>
          <VuesaxLinearArrowLef />
          <Home>{`home`}</Home>
        </Frame6>
        <Frame7>
          <Faq>{`FAQ`}</Faq>
          <VuesaxLinearArrowRig />
        </Frame7>
      </Frame8>
      <Frame51>
        <Frame52>
          <HelloMyNameIsBrandon>
            {`Hello, my name is Brandon Bennett
i’m a software developer & Music Producer from nyc
and this is my website

i have more projects on my github.
feel free to learn more about me there!

`}
          </HelloMyNameIsBrandon>
        </Frame52>
      </Frame51>
      <Frame3>
        <NavigationBars>
          <Sr>{`SR`}</Sr>
          <Frame53>
            <Options1 />
          </Frame53>
          <Buttons />
        </NavigationBars>
      </Frame3>
    </AboutUs1>
  );
}

export default AboutUs;
