/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/
import { Link } from 'react-router-dom';
import React from 'react';
import VectorImage from 'src/components/Pages/CreateRooms/assets/images/Rooms_Vector.png';
import Vector1Image from 'src/components/Pages/CreateRooms/assets/images/Rooms_Vector_1.png';
import Vector2Image from 'src/components/Pages/CreateRooms/assets/images/Rooms_Vector_2.png';
import Vector3Image from 'src/components/Pages/CreateRooms/assets/images/Rooms_Vector_3.png';
import Vector4Image from 'src/components/Pages/CreateRooms/assets/images/Rooms_Vector_4.png';
import Vector5Image from 'src/components/Pages/CreateRooms/assets/images/Rooms_Vector_5.png';
import Vector6Image from 'src/components/Pages/CreateRooms/assets/images/Rooms_Vector_6.png';
import { styled } from '@mui/material/styles';
// import VuesaxLinearArrowLeft from 'src/components/VuesaxLinearArrowLeft/VuesaxLinearArrowLeft';
import Options from 'src/components/Options/Options';
// import Buttons from 'src/components/Buttons/Buttons';
import TableDefault from 'src/components/Pages/CreateRooms/components/TableDefault/TableDefault.jsx';

const Rooms1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: `1440px`,
  height: `1117px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const FrequentQuestions = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1440px`,
  height: `1117px`,
  left: `0px`,
  top: `0px`,
});

const FrequentQuestions1 = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 1)`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1440px`,
  height: `1117px`,
  left: `0px`,
  top: `0px`,
  overflow: `hidden`,
});

const Frame8 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `flex-start`,
  padding: `0px 80px`,
  boxSizing: `border-box`,
  width: `1728px`,
  left: `0px`,
  top: `50px`,
});

const Frame6 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
});

// const VuesaxLinearArrowLef = styled(VuesaxLinearArrowLeft)(({ theme }) => ({
//   width: `40px`,
//   height: `40px`,
//   margin: `0px`,
// }));

const AboutUs = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `32px`,
  letterSpacing: `-1.6px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `uppercase`,
  margin: `0px 0px 0px 20px`,
});

const SocialNetworksDark = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  width: `400px`,
});

const Instagram = styled('div')({
  border: `1px solid rgba(255, 255, 255, 1)`,
  boxSizing: `border-box`,
  borderRadius: `10px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `6px`,
});

const Instagram1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  height: `40px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Vector = styled('img')({
  height: `22.15px`,
  width: `22.18px`,
  position: `absolute`,
  left: `10px`,
  top: `8px`,
});

const Vector1 = styled('img')({
  height: `38px`,
  width: `38px`,
  position: `absolute`,
  left: `1px`,
  top: `1px`,
});

const Figma = styled('div')({
  border: `1px solid rgba(255, 255, 255, 1)`,
  boxSizing: `border-box`,
  borderRadius: `10px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `6px`,
});

const FacebookLogo2019 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  height: `40px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Vector2 = styled('img')({
  height: `39.76px`,
  width: `40px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector3 = styled('img')({
  height: `32.19px`,
  width: `17.11px`,
  position: `absolute`,
  left: `12px`,
  top: `8px`,
});

const LinkedIn = styled('div')({
  border: `1px solid rgba(255, 255, 255, 1)`,
  boxSizing: `border-box`,
  borderRadius: `10px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `6px`,
});

const Youtube = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  height: `40px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Vector4 = styled('img')({
  height: `25.78px`,
  width: `36.69px`,
  position: `absolute`,
  left: `2px`,
  top: `7px`,
});

const Telegram = styled('div')({
  border: `1px solid rgba(255, 255, 255, 1)`,
  boxSizing: `border-box`,
  borderRadius: `10px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `6px`,
});

const Tiktok = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  height: `40px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Vector5 = styled('img')({
  height: `27.12px`,
  width: `24px`,
  position: `absolute`,
  left: `8px`,
  top: `6px`,
});

const Twitter = styled('div')({
  border: `1px solid rgba(255, 255, 255, 1)`,
  boxSizing: `border-box`,
  borderRadius: `10px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `6px`,
});

const Twitter1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `40px`,
  height: `40px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Vector6 = styled('img')({
  height: `30.25px`,
  width: `37.14px`,
  position: `absolute`,
  left: `1px`,
  top: `5px`,
});

const Frame3 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1639px`,
  height: `100px`,
  left: `-44px`,
  top: `947px`,
});

const NavigationBars = styled('div')({
  backgroundColor: `rgba(27, 27, 27, 1)`,
  boxShadow: `0px 0px 50px rgba(0, 0, 0, 0.23)`,
  borderRadius: `100px`,
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `20px 100px`,
  boxSizing: `border-box`,
  width: `1340px`,
  left: `88px`,
  top: `20px`,
  overflow: `hidden`,
});

const We = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Newake`,
  fontWeight: `400`,
  fontSize: `36px`,
  letterSpacing: `-1.8px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `capitalize`,
});

const Frame54 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `10px`,
  boxSizing: `border-box`,
  left: `144px`,
  top: `126px`,
});

const TableDefault1 = styled(TableDefault)(({ theme }) => ({
  height: `783px`,
  width: `1181.33px`,
  margin: `0px`,
}));

function Rooms(props) {
  return (
    <Rooms1 className={props.className}>
      <FrequentQuestions>
        <FrequentQuestions1>
          <Frame8>
            <Frame6>
              {/* <VuesaxLinearArrowLef /> */}
              <AboutUs><Link to={"/"}>{`HOME`}</Link></AboutUs>
            </Frame6>
            <SocialNetworksDark>
              {false && (
                <Instagram>
                  <Instagram1>
                    <Vector src={VectorImage} loading="lazy" alt={'Vector'} />
                    <Vector1 src={Vector1Image} loading="lazy" alt={'Vector'} />
                  </Instagram1>
                </Instagram>
              )}
              {false && (
                <Figma>
                  <FacebookLogo2019>
                    <Vector2 src={Vector2Image} loading="lazy" alt={'Vector'} />
                    <Vector3 src={Vector3Image} loading="lazy" alt={'Vector'} />
                  </FacebookLogo2019>
                </Figma>
              )}
              {false && (
                <LinkedIn>
                  <Youtube>
                    <Vector4 src={Vector4Image} loading="lazy" alt={'Vector'} />
                  </Youtube>
                </LinkedIn>
              )}
              {false && (
                <Telegram>
                  <Tiktok>
                    <Vector5 src={Vector5Image} loading="lazy" alt={'Vector'} />
                  </Tiktok>
                </Telegram>
              )}
              {false && (
                <Twitter>
                  <Twitter1>
                    <Vector6 src={Vector6Image} loading="lazy" alt={'Vector'} />
                  </Twitter1>
                </Twitter>
              )}
            </SocialNetworksDark>
          </Frame8>
          <Frame3>
            <NavigationBars>
              <We>{`SR`}</We>
              <Options />
              {/* <Buttons /> */}
            </NavigationBars>
          </Frame3>
        </FrequentQuestions1>
        <Frame54>
          <TableDefault1 />
        </Frame54>
      </FrequentQuestions>
    </Rooms1>
  );
}

export default Rooms;
