/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Helmet } from 'react-helmet';
import Image1Image from 'src/components/Pages/About/src/assets/images/Web_Image.png';
import LinkedInImage from 'src/assets/images/Web_LinkedIn.svg';
import TwitterImage from 'src/assets/images/Web_Twitter.svg';
import Image2Image from 'src/components/Pages/About/src/assets/images/Web_Image_1.png';
import { styled } from '@mui/material/styles';
import Options from 'src/components/Options/Options';
// import Buttons from 'src/components/Buttons/Buttons';

const Web1 = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: 'auto',
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
  width: 'fit-content',
});

const Frame8 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `80px`,
  width: `1440px`,
});

const SocialNetworksDark = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `400px`,
  height: `80px`,
  left: `80px`,
  top: `0px`,
});

const Image1 = styled('img')({
  height: `52px`,
  width: `52px`,
  objectFit: `cover`,
});

const LinkedIn = styled('img')({
  height: `auto`,
  width: `51px`,
});

const Twitter = styled('img')({
  height: `auto`,
  width: `52px`,
});

const Frame7 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `1117px`,
  top: `0px`,
});

const AboutUs = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Poppins`,
  fontWeight: `400`,
  fontSize: `32px`,
  letterSpacing: `-1.6px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `uppercase`,
  margin: `0px`,
});

const Frame48 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  width: `80px`,
  margin: `0px 0px 0px 20px`,
});

const Frame50 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px 0px 10px 10px`,
  boxSizing: `border-box`,
});

const Image2 = styled('img')({
  height: `1103.5px`,
  width: `1424px`,
  objectFit: `cover`,
  margin: `0px`,
});

const NavigationBars = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(27, 27, 27, 1)`,
  boxShadow: `0px 0px 50px rgba(151, 71, 255, 0.08)`,
  borderRadius: `100px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `80px`,
  width: `1440px`,
  overflow: `hidden`,
}));

const Sr = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Newake`,
  fontWeight: `400`,
  fontSize: `36px`,
  letterSpacing: `-1.8px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `capitalize`,
  position: `absolute`,
  left: `24px`,
  top: `22px`,
});

const Options1 = styled(Options)(({ theme }) => ({
  position: `absolute`,
  left: `502px`,
  top: `30px`,
}));

// const Buttons1 = styled(Buttons)(({ theme }) => ({
//   position: `absolute`,
//   left: `1231px`,
//   top: `20px`,
// }));

function AboutPage(props) {
  return (
    <Web1 className={props.className}>
      <Helmet>
        <title>Web</title>
      </Helmet>
      <Frame8>
        <SocialNetworksDark>
          <Image1 src={Image1Image} loading="lazy" alt={'Image'} />
          <LinkedIn src={LinkedInImage} loading="lazy" alt={'LinkedIn'} />
          <Twitter src={TwitterImage} loading="lazy" alt={'Twitter'} />
        </SocialNetworksDark>
        <Frame7>
          <AboutUs>{`ABOUT US`}</AboutUs>
          <Frame48></Frame48>
        </Frame7>
      </Frame8>
      <Frame50>
        <Image2 src={Image2Image} loading="lazy" alt={'Image'} />
      </Frame50>
      <NavigationBars>
        <Sr>{`SR`}</Sr>
        <Options1 />
        {/* <Buttons1 /> */}
      </NavigationBars>
    </Web1>
  );
}

export default AboutPage;
