/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Helmet } from 'react-helmet';
import { styled } from '@mui/material/styles';
import { Link } from 'react-router-dom';

const Options1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: 'auto',
  width: 'fit-content',
});

const Text = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Gotham`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `-1px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `none`,
  margin: `0px`,
});

const Text1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `italic`,
  fontFamily: `GothamBook`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `-1px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `none`,
  margin: `0px 0px 0px 30px`,
});

const Text2 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `italic`,
  fontFamily: `GothamBook`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `-1px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `none`,
  margin: `0px 0px 0px 30px`,
});

const Text3 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(41, 41, 41, 1)`,
  fontStyle: `italic`,
  fontFamily: `GothamBook`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `-1px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `none`,
  margin: `0px 0px 0px 30px`,
}));

function Options(props) {
  return (
    <Options1 className={props.className}>
      <Helmet>
        <title>Options</title>
      </Helmet>
      <Text>{`Home`}</Text>
      <Link to="/rooms"><Text1>{`Create Room`}</Text1></Link>
      <Text2>{`FAQ`}</Text2>
      {false && <Text3>{`News`}</Text3>}
    </Options1>
  );
}

export default Options;
